# Generated by Django 4.0.6 on 2023-06-09 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=16)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('is_new_patient', models.BooleanField(default=True)),
                ('patient_token', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPrimaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=16, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=17)),
                ('guardian_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(default='', max_length=250)),
            ],
        ),
    ]
