# Generated by Django 4.0.6 on 2023-06-12 08:33

from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rp_alter_ft_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rp',
            name='report_file',
            field=models.FileField(upload_to=patient.models.get_report_upload_path),
        ),
        migrations.CreateModel(
            name='PHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('pulse', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('diabetic_level', models.CharField(blank=True, max_length=100, null=True)),
                ('phi', models.TextField(max_length=1000)),
                ('pov', models.TextField(max_length=300)),
                ('remarks', models.TextField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata')),
            ],
        ),
    ]
